name: Sync to internal repo

on:
  push:
    branches: [main]

jobs:
  sync:
    if: github.repository == 'bluesky-social/atproto'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ vars.SYNC_INTERNAL_APP_ID }}
          private-key: ${{ secrets.SYNC_INTERNAL_PK }}
          repositories: atproto-internal
      - name: Push to internal repo
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name "github-actions"
          git config user.email "test@users.noreply.github.com"
          git config --unset-all http.https://github.com/.extraheader
          git remote add internal https://x-access-token:${TOKEN}@github.com/bluesky-social/atproto-internal.git
          git push internal main --force
